### ISSUE TITLE
[New Data Source]: Add `cloudavenue_org_vdc`

### ISSUE THREAD

**Issue by MrRometo** [orange-cloudavenue/terraform-provider-cloudavenue#101]
### Description

Provides a VMware Cloud Director org_vdc data source. This can be used to get org_vdc

### Requested Resource(s) and/or Data Source(s)

`cloudavenue_org_vdc`

### Potential Terraform Configuration

```terraform
data "vcd_org_vdc" "my-org-vdc" {
  org  = "cav01ev01ocb0006205"
  name = "MyVDC"
}
```

### References

https://registry.terraform.io/providers/vmware/vcd/latest/docs/data-sources/org_vdc

### Would you like to implement a fix?

None

**Comment by gaetanars** [comment]
This resource already exist, it's named `cloudavenue_vdc`
