### ISSUE TITLE
[New Resource]: Add `cloudavenue_vm_inserted_media`

### ISSUE THREAD

**Issue by MrRometo** [orange-cloudavenue/terraform-provider-cloudavenue#110]
### Description

Provides a Cloud Avenue resource for inserting or ejecting media (ISO) file for the VM. Create this resource for inserting the media, and destroy it for ejecting.

### Requested Resource(s) and/or Data Source(s)

`cloudavenue_vm_inserted_media`

### Potential Terraform Configuration

```terraform
resource "cloudavenue_vm_inserted_media" "myInsertedMedia" {
  vdc     = "VDC_Frangipane"
  catalog = "my-catalog_romain"
  name    = "Office_2016_STD_FR.iso"

  vapp_name = "vapp_test3"
  vm_name   = "TestRomain"

  eject_force = true
}
```

### References

https://registry.terraform.io/providers/vmware/vcd/latest/docs/resources/inserted_media

### Would you like to implement a fix?

None

**Comment by azrod** [comment]
I'm propose to rename this resource to `cloudavenue_vapp_inserted_media`

@eremid @gaetanars @dmicheneau ?

**Comment by dmicheneau** [comment]
Find Bug when ejected media resource:
```
TF_ACC=1 go test -v ./internal/tests/vm -run TestAccVMInsertedMediaResource
=== RUN   TestAccVMInsertedMediaResource
    vm_inserted_media_resource_test.go:28: Step 1/1 error: Check failed: 1 error occurred:
                * Check 7/7 error: cloudavenue_vm_inserted_media.example: Attribute 'eject_force' expected "true", got "false"
        
    testing_new.go:82: Error running post-test destroy, there may be dangling resources: exit status 1
--- FAIL: TestAccVMInsertedMediaResource (20.79s)
FAIL
FAIL    github.com/orange-cloudavenue/terraform-provider-cloudavenue/internal/tests/vm  20.806s
FAIL
```
The bug exist also with the VCD provider.

**Comment by dmicheneau** [comment]
https://github.com/vmware/go-vcloud-director/issues/552
