### ISSUE TITLE
[New Resource]: Add `cloudavenue_security_tag`

### ISSUE THREAD

**Issue by MrRometo** [orange-cloudavenue/terraform-provider-cloudavenue#113]
### Description

Provides a VMware Cloud Director SECURITY_TAG resource. This can be used to create, modify, and delete SECURITY_TAG.

### Requested Resource(s) and/or Data Source(s)

`cloudavenue_security_tag`

### Potential Terraform Configuration

```terraform
resource "vcd_catalog" "myNewCatalog" {

  name             = "my-catalog_romain"
  description      = "catalog for files"
  delete_recursive = true
  delete_force     = true
}

data "vcd_catalog" "cat-datacloud" {
  name = "my-catalog_romain"
}

data "vcd_catalog_vapp_template" "debian_10_X64" {
  catalog_id = data.vcd_catalog.cat-datacloud.id
  name       = "debian_10_X64"
}

resource "vcd_vm" "TestVm" {
  name = "TestVm_romain"

  vapp_template_id = data.vcd_catalog_vapp_template.debian_10_X64.id
  cpus             = 2
  memory           = 2048

}

resource "vcd_security_tag" "my_tag" {
  name   = "test-tag-romain"
  vm_ids = [vcd_vm.TestVm.id]
}
```

### References

https://registry.terraform.io/providers/vmware/vcd/latest/docs/resources/security_tag

### Would you like to implement a fix?

None

**Comment by MrRometo** [comment]
Require template "debian_10_X64" in catalog

**Comment by azrod** [comment]
Blocked by https://github.com/orange-cloudavenue/terraform-provider-cloudavenue/issues/94
