### ISSUE TITLE
[New Data Source]: `cloudavenue_resource_list`

### ISSUE THREAD

**Issue by MrRometo** [orange-cloudavenue/terraform-provider-cloudavenue#138]
### Description

Add datasource cloudavenue_resource_list

### Requested Resource(s) and/or Data Source(s)

`cloudavenue_resource_list`

### Potential Terraform Configuration

```terraform
data "vcd_resource_list" "list_of_orgs" {
  name          = "list_of_orgs"
  resource_type = "vcd_org"
  list_mode     = "name"
}

# Shows the list of organizations
output "org_list" {
  value = data.vcd_resource_list.list_of_orgs.list
}
```

### References

https://registry.terraform.io/providers/vmware/vcd/latest/docs/data-sources/resource_list

### Would you like to implement a fix?

None

**Comment by dmicheneau** [comment]
This resource is used like a generic datasource. 
Is not a good practice in terraform provider.
We close this unsual resource.
