### ISSUE TITLE
[New Data Source]: `cloudavenue_resource_schema`

### ISSUE THREAD

**Issue by MrRometo** [orange-cloudavenue/terraform-provider-cloudavenue#139]
### Description

Add datasource  `cloudavenue_resource_schema`

### Requested Resource(s) and/or Data Source(s)

`cloudavenue_resource_schema`

### Potential Terraform Configuration

```terraform
data "vcd_resource_schema" "org_struct" {
  name          = "org_struct"
  resource_type = "vcd_org"
}

// Shows the organization attributes
output "org_struct" {
  value = data.vcd_resource_schema.org_struct.attributes
}
```

### References

https://registry.terraform.io/providers/vmware/vcd/latest/docs/data-sources/resource_schema

### Would you like to implement a fix?

None

**Comment by dmicheneau** [comment]
This is an usual use case of datasource, and it's not a good practice of terraform provider.
