### ISSUE TITLE
[New Data Source]: `cloudavenue_storage_profile`

### ISSUE THREAD

**Issue by MrRometo** [orange-cloudavenue/terraform-provider-cloudavenue#141]
### Description

Add datasource cloudavenue_storage_profile

### Requested Resource(s) and/or Data Source(s)

`cloudavenue_storage_profile`

### Potential Terraform Configuration

```terraform
data "vcd_storage_profile" "sp" {
  name = "gold"
}

output "sp" {
  value = data.vcd_storage_profile.sp
}
```

### References

https://registry.terraform.io/providers/vmware/vcd/latest/docs/data-sources/storage_profile

### Would you like to implement a fix?

None

**Comment by dmicheneau** [comment]
Need to discuss on this datasource needs.
