### ISSUE TITLE
[New Data Source]: `cloudavenue_task`

### ISSUE THREAD

**Issue by MrRometo** [orange-cloudavenue/terraform-provider-cloudavenue#142]
### Description

Add datasource `cloudavenue_task`

### Requested Resource(s) and/or Data Source(s)

`cloudavenue_task`

### Potential Terraform Configuration

```terraform
data "vcd_task" "some-task" {
  id = "e522058d-30dd-4228-be2b-eadcb14a12f9"
}

output "some-task" {
  value = data.vcd_task.some-task
}
```

### References

https://registry.terraform.io/providers/vmware/vcd/latest/docs/data-sources/task

### Would you like to implement a fix?

None

**Comment by dmicheneau** [comment]
This is an usual use case of datasource, not a good practice of terraform provider.
We close this issue.
