### ISSUE TITLE
[New Data Source]: JOBS

### ISSUE THREAD

**Issue by dmicheneau** [orange-cloudavenue/terraform-provider-cloudavenue#17]
### Description

Add  cloudavenue_jobs

[/api/customers/v1.0/jobs/{Job-Id}](https://swagger.cloudavenue.orange-business.com/#/Jobs)

### Requested Resource(s) and/or Data Source(s)

Add cloudavenue_jobs

### Would you like to implement a fix?

None

**Comment by azrod** [comment]
For me jobs is not datasource. 

Job is temporary value and is used in terraform code for validate is job is success or not.

**Comment by azrod** [comment]
@eremid @gaetanars ?
