### ISSUE TITLE
[New Data Source]: VDC (list)

### ISSUE THREAD

**Issue by MrRometo** [orange-cloudavenue/terraform-provider-cloudavenue#23]
### Description

[SwaggerVdcsList](https://swagger.cloudavenue.orange-business.com/#/vDC/get_api_customers_v2_0_vdcs)

### Requested Resource(s) and/or Data Source(s)

Add `cloudavenue_vdcs`

**Comment by azrod** [comment]
This datasource is already implemented (PR #6)
