### ISSUE TITLE
[New Data Source]: `cloudavenue_network_routed`

### ISSUE THREAD

**Issue by valentin-dubreuil** [orange-cloudavenue/terraform-provider-cloudavenue#238]
### Description

Add datasource `cloudavenue_network_routed`

### Requested Resource(s) and/or Data Source(s)

`cloudavenue_network_routed`

### Potential Terraform Configuration

```terraform
resource "vcd_network_routed_v2" "nsxt-backed" {
  name        = "nsxt-routed 1"
  description = "My routed Org VDC network backed by NSX-T"

  gateway       = "1.1.1.1"
  prefix_length = 24

  static_ip_pool {
    start_address = "1.1.1.10"
    end_address   = "1.1.1.20"
  }

  static_ip_pool {
    start_address = "1.1.1.100"
    end_address   = "1.1.1.103"
  }
}

data "vcd_network_routed_v2" "nsxt-backed" {
  name     = "nsxt-routed 1"
}

output "network_routed_v2_id" {
  value = data.vcd_network_routed_v2.nsxt-backed.id
}
```

### References

https://registry.terraform.io/providers/vmware/vcd/latest/docs/data-sources/network_routed_v2

### Would you like to implement a fix?

None

**Comment by azrod** [comment]
The name of the datasource is `cloudavenue_network_routed` and not `cloudavenue_network_routed_v2`
