### ISSUE TITLE
[New Data Source]: VDC (name) 

### ISSUE THREAD

**Issue by MrRometo** [orange-cloudavenue/terraform-provider-cloudavenue#24]
### Description

[SwaggerVdcName](https://swagger.cloudavenue.orange-business.com/#/vDC/get_api_customers_v2_0_vdcs__vdc_name_)

### Requested Resource(s) and/or Data Source(s)

Add `cloudavenue_vdcs_vdcname`

**Comment by azrod** [comment]
This datasource is already implemented (PR #6)
