### ISSUE TITLE
[Enhancement]: Add dynamic list for Hardware-version supported and OS Types

### ISSUE THREAD

**Issue by dmicheneau** [orange-cloudavenue/terraform-provider-cloudavenue#305]
### Description

- Need To dynamically generate hardware version of your VM creation in iso mode installation or empty VM.
This attributes is require by VMware  when you create your VM.

- Need to dynamically generate OsTypes version of your VM creation in iso mode installation or empty VM.
This attributes is require by VMware when you create your VM.

### Affected Resource(s) and/or Data Source(s)

* cloudavenue_vm

### Would you like to implement a fix?

None

**Comment by azrod** [comment]
Fix #658
