### ISSUE TITLE
[Docs]: Add Hot and Cold update for `cloudavenue_vm`

### ISSUE THREAD

**Issue by azrod** [orange-cloudavenue/terraform-provider-cloudavenue#308]
### Documentation Link

https://registry.terraform.io/providers/orange-cloudavenue/cloudavenue/latest/docs/resources/vm

### Description

For each attributes add if allow hot or cold update

### Would you like to implement a fix?

None

**Comment by dmicheneau** [comment]
We could make a validator to handle cold attributes that require a VM restart.
