### ISSUE TITLE
[Bug]: Can't delete last VDC of a VDCGroup

### ISSUE THREAD

**Issue by gaetanars** [orange-cloudavenue/terraform-provider-cloudavenue#58]
Bug due to the API structure

### Terraform Core Version

1.3.8

### Cloud Avenue Provider Version

dev

### Affected Resource(s)

* cloudavenue_vdc

### Expected Behavior

terraform destroy must destroy the VDC

### Actual Behavior

If the VDC is the last of a VDCGroup, the VDC is not deleted and we have an error : 

`Could not delete vdc, unexpected error: 404 Not Found`

### Terraform Configuration Files

```hcl
resource "cloudavenue_vdc" "example" {
  name                  = "MyVDC"
  vdc_group             = "MyVDCGroup"
  description           = "Example VDC created by Terraform"
  cpu_allocated         = 11000
  memory_allocated      = 10
  cpu_speed_in_mhz      = 2200
  billing_model         = "PAYG"
  disponibility_class   = "ONE-ROOM"
  service_class         = "STD"
  storage_billing_model = "PAYG"

  storage_profile = [
    {
      class   = "gold"
      default = true
      limit   = 500
    },
    {
      class   = "silver"
      default = false
      limit   = 500
    },
  ]
}
```

### Steps to Reproduce

terraform apply
terraform destroy

### Would you like to implement a fix?

None

**Comment by azrod** [comment]
Now if you manage your VDCGroup by the resource `cloudavenue_vdc_group` it's possible to remove the vdcGroup
