### ISSUE TITLE
[Bug]: Unsupported Dedicated Storage Profile Class

### ISSUE THREAD

**Issue by Yobar73** [orange-cloudavenue/terraform-provider-cloudavenue#615]
### Terraform Core Version

1.5.3

### Cloud Avenue Provider Version

0.14.0

### Affected Resource(s)

cloudavenue_vdc
maybe all resources depending storage_profile

### Expected Behavior

We want to be able to import the dedicated storage profile class onto our existing infrastructure and use it into our infrastructure as code

### Actual Behavior

Our existing VDC has been updated adding the dedicate storage profile. When we try to import the VDC updated by Orange, we have an issue "Unsupported Dedicated Storage Profile Class silver_xxxxxxxxxx"

### Relevant Error/Panic Output Snippet

```shell
╷
│ Error: Unsupported Dedicated Storage Profile Class (HTTP Code => 400)
│ 
│   with cloudavenue_vdc.my_vdc,
│   on file.tf line xx, in resource "cloudavenue_vdc" "my_vdc":
│   31: resource "cloudavenue_vdc" "my_vdc" {
│ 
│ Unsupported Dedicated Storage Profile Class silver_xxxxxxxx
╵
```

### Terraform Configuration Files

```hcl
terraform {
  required_providers {
    cloudavenue = {
      source  = "orange-cloudavenue/cloudavenue"
    }
    vcd = {
      source  = "vmware/vcd"
    }
  }
}

provider "cloudavenue" {
}
provider "vcd" {
}
```

### Steps to Reproduce

Ask to Orange to add a dedicated storage profile onto your VDC and try to import it

### Would you like to implement a fix?

None

**Comment by azrod** [comment]
Hi @Yobar73 👋 
Thank you for reporting this issue and sorry you are running into this unexpected behavior.

Please provide your terraform configuration for the resource `"cloudavenue_vdc" "my_vdc"`

We support this issue and will let you know when the fix is ​​released.

**Comment by azrod** [comment]
@Yobar73 thanks for your feedback. 
After investigation the problem il know in CloudAvenue API and the issue has been priorized in backlog.

Once the API is corrected we will quickly make the necessary changes in the terraform provider.

**Comment by Yobar73** [comment]
@azrod  Do you have any news on the correction of this bug on CloudAvenue API?

**Comment by azrod** [comment]
Hi @Yobar73,

This bug has fixed last week in the CloudAvenue API. We working on implement change on terraform provider. We will publish a new release soon with the fix.

**Comment by azrod** [comment]
# 🚀  Release v0.18.0

Hi @Yobar73. The terraform provider has been release. This release contains the fix of your bug. Please try this release. Do not hesitate to re-open issue if your bug is not fixed.
