### ISSUE TITLE
[Bug]: Lease values issue

### ISSUE THREAD

**Issue by mydoomfr** [orange-cloudavenue/terraform-provider-cloudavenue#617]
### Terraform Core Version

1.5.7

### Cloud Avenue Provider Version

0.14.0

### Affected Resource(s)

cloudavenue_vapp

### Expected Behavior

I expect the defined "Lease" object values to be successfully applied.
After running `terraform plan/apply`, there should be no changes.

### Actual Behavior

The next `terraform plan/apply` show that the Lease object values are ignored and gets the default values of 3600

### Relevant Error/Panic Output Snippet

```shell
# cloudavenue_vapp.vapp will be updated in-place
  ~ resource "cloudavenue_vapp" "vapp" {
        id               = "urn:vcloud:vapp:6db7dfcb-4c6a-450b-b67e-0e63d93fa778"
      ~ lease            = {
          ~ runtime_lease_in_sec = 3600 -> 42
          ~ storage_lease_in_sec = 3600 -> 69
        }
        name             = "vapp-test"
        # (3 unchanged attributes hidden)
    }
```

### Terraform Configuration Files

```terraform
resource "cloudavenue_vapp" "vapp" {
  name             = "vapp-test"
  lease            = {
    runtime_lease_in_sec = 42
    storage_lease_in_sec = 69
  }
}
```

### Steps to Reproduce

# apply twice
`terraform apply`
`terraform apply`

### Would you like to implement a fix?

None

**Comment by azrod** [comment]
Hi @mydoomfr 👋
Thank you for reporting this issue and sorry you are running into this unexpected behavior.

We support this issue and will let you know when the fix is ​​released.
