### ISSUE TITLE
[Network Routed] Resource will be recreated a each apply if `static_ip_pool` is not set

### ISSUE THREAD

**Issue by azrod** [orange-cloudavenue/terraform-provider-cloudavenue#666]
In resource `cloudavenue_network_routed` if `static_ip_pool` attribute is null, the resource will be recreated a each apply. 
This is a bug.

**Comment by azrod** [comment]
**workaround**

Set `static_ip_pool    = []` in tf configuration. 

This resource requires refacto.

**Comment by o-presentini** [comment]
Workaround not work.
Entry = [] raise an error : list cannot be empty
