### ISSUE TITLE
[Bug]: Unsupported Dedicated Storage Profile Class

### ISSUE THREAD

**Issue by Yobar73** [orange-cloudavenue/terraform-provider-cloudavenue#721]
### Terraform Core Version

1.5.3

### Cloud Avenue Provider Version

0.18.0

### Affected Resource(s)

resource.cloudavenue_vdc

This issue is the continuity of following ticket https://github.com/orange-cloudavenue/terraform-provider-cloudavenue/issues/615

### Expected Behavior

We want to be able to import the dedicated storage profile class onto our existing infrastructure and use it into our infrastructure as code

### Actual Behavior

Our existing VDC has been updated adding the dedicate storage profile. When we try to import the VDC updated by Orange, we have an issue "Error: Storage profile class attribute is not valid"

│ storage profile class not found: silver_xxxxxxxxxx (Allowed values:
│ [silver silver_r1 silver_r2 gold gold_r1 gold_r2 gold_hm platinum3k
│ platinum3k_r1 platinum3k_r2 platinum3k_hm platinum7k platinum7k_r1
│ platinum7k_r2 platinum7k_hm])

### Relevant Error/Panic Output Snippet

Our existing VDC has been updated adding the dedicate storage profile. When we try to import the VDC updated by Orange, we have an issue "Error: Storage profile class attribute is not valid"

### Terraform Configuration Files

terraform {
  required_providers {
    cloudavenue = {
      source  = "orange-cloudavenue/cloudavenue"
      version = "0.18.0"
    }
    vcd = {
      source  = "vmware/vcd"
    }
  }
}

provider "cloudavenue" {
}
provider "vcd" {
}

resource "cloudavenue_vdc" "my_vdc" {
  name                  = "my_vdc"
  ...
  service_class         = "STD"

  storage_profiles = [
            {
                class   = "platinum7k_xxxxxxxxxx"
                default = false
                limit   = 10237
            },
   ]
}

### Steps to Reproduce

Ask to Orange to add a dedicated storage profile onto your VDC and try to import it

### Would you like to implement a fix?

None

**Comment by azrod** [comment]
Hi @Yobar73 

Sorry for the inconvenience.

Please provide entire error message.

Regards

**Comment by azrod** [comment]
Hello. 

Please try a fixed version [v0.18.2](https://github.com/orange-cloudavenue/terraform-provider-cloudavenue/releases/tag/v0.18.2)

Regards

**Comment by Yobar73** [comment]
I tried the version 0.18.2 and I confirm that this version actually fixes the problem. Thank you
