### ISSUE TITLE
[Bug]: Error when reapplying bucket creation

### ISSUE THREAD

**Issue by jbphilippe-orange** [orange-cloudavenue/terraform-provider-cloudavenue#738]
### Terraform Core Version

1.7.4

### Cloud Avenue Provider Version

0.18.2

### Affected Resource(s)

cloudavenue_s3_bucket

### Expected Behavior

It should says  `cloudavenue_s3_bucket.tina_bucket: Refreshing state...`  

### Actual Behavior

```
cloudavenue_s3_bucket.tina_bucket: Creating...
╷
│ Error: Error creating bucket
│ 
│   with cloudavenue_s3_bucket.tina_bucket,
│   on main.tf line 11, in resource "cloudavenue_s3_bucket" "tina_bucket":
│   11: resource "cloudavenue_s3_bucket" "tina_bucket" {
│ 
│ Error creating bucket (name=customer-backup-tina-vapp): BucketAlreadyOwnedByYou: A bucket with this name
│ exists and is already owned by you
│       status code: 409, request id: 52e696fa0540b4058a38, host id: 52e696fa0540b4058a38
```

### Terraform Configuration Files

```
resource "cloudavenue_s3_bucket" "tina_bucket" {
  name = "customer-backup-tina-vapp"
}
```

### Steps to Reproduce

`terraform init`
`terraform plan`
`terraform apply` 

Try to launch again `terraform apply`

### Would you like to implement a fix?

None

**Comment by dmicheneau** [comment]
Hello, can you try deleting your bucket first.
It seems that your bucket already exists (see the error message).

**Comment by jbphilippe-orange** [comment]
I don't know what happened,  but with the last version of the provider and a "terraform import" , it works.
