### ISSUE TITLE
[Bug]: Environment variable CLOUDAVENUE_USER not taken

### ISSUE THREAD

**Issue by yfe-ob** [orange-cloudavenue/terraform-provider-cloudavenue#739]
### Terraform Core Version

1.5.7

### Cloud Avenue Provider Version

0.18.2

### Affected Resource(s)

provider "cloudavenue" {
}

### Expected Behavior

Setting up the environment variable :
export export CLOUDAVENUE_USER="my-user"

Do a terraform plan

### Actual Behavior

The environement variable CLOUDAVENUE_USER is ignored

### Relevant Error/Panic Output Snippet

```shell
│ Error: Attribute is empty
│ 
│   with provider["registry.terraform.io/orange-cloudavenue/cloudavenue"],
│   on provider.tf line 10, in provider "cloudavenue":
│   10: provider "cloudavenue" {
│ 
│ the username is empty
```

### Terraform Configuration Files

provider.TF

terraform {
  required_providers {
    cloudavenue = {
      source = "orange-cloudavenue/cloudavenue"
      version = "0.18.2"
    }
  }
}

provider "cloudavenue" {
}

### Steps to Reproduce

terraform plan

### Would you like to implement a fix?

None

**Comment by azrod** [comment]
Hi @yfe-ob,

This change has announced in release [v0.18.0](https://github.com/orange-cloudavenue/terraform-provider-cloudavenue/releases/tag/v0.18.0).  

Please read the changelog. 

Best
