### ISSUE TITLE
[Bug]: `cloudavenue_edgegateway` resource are no longer found

### ISSUE THREAD

**Issue by matmb-cld** [orange-cloudavenue/terraform-provider-cloudavenue#765]
### Terraform Core Version

1.9.2

### Cloud Avenue Provider Version

0.18.4

### Affected Resource(s)

* cloudavenue_edgegateway

### Expected Behavior

terraform plan should return
` No changes. Your infrastructure matches the configuration.`

### Actual Behavior

terraform plan returns:
`Planning failed. Terraform encountered an error while generating this plan.`

### Relevant Error/Panic Output Snippet

```shell
╷
│ Error: Error retrieving edge gateway
│ 
│ error on get edge gateway: ErrorCode:nf-0004 - ErrorReason:Resource not found - ErrorMessage:Tier1 with id urn:vcloud:gateway:10ae72f1-eb7b-4029-8c9d-381cdf3ac8cb not found
╵
╷
│ Error: Error retrieving edge gateway
│ 
│   with cloudavenue_edgegateway.test,
│   on test.tf line 5, in resource "cloudavenue_edgegateway" "test":
│    5: resource "cloudavenue_edgegateway" "test" {
│ 
│ error on get edge gateway: ErrorCode:nf-0004 - ErrorReason:Resource not found - ErrorMessage:Tier1 with id urn:vcloud:gateway:e14869ed-3883-43e7-b6cf-9c94f5e98a57 not found
```

### Terraform Configuration Files
```hcl
terraform {

  required_providers {
    cloudavenue = {
      source  = "orange-cloudavenue/cloudavenue"
      version = "0.18.4"
    }
  }
}

provider "cloudavenue" {
  org      = "myorg"
  user     = "myuser"
  password = "mypass"
}

data "cloudavenue_tier0_vrfs" "this" {}

resource "cloudavenue_edgegateway" "test" {
  owner_name = "obsitlabiaas"
  tier0_vrf_name = data.cloudavenue_tier0_vrfs.this.names[0]
  owner_type     = "vdc"
  bandwidth      = 100 # Max value is 300 Mb
}
```

### Steps to Reproduce

1. Create or import a cloudavenue_edgegateway with `terraform apply` or `terraform  import cloudavenue_edgegateway.test EdgeGWName`
2. Perform `terraform plan`

### Important Factoids

This issue impacts all the cloudavenue_edgegateway resources I've created few weeks ago.
Few weeks ago there was no issue.
I guess some changes must have been applied on Cloud Avenue infrastructure that could explain this problem.

### Would you like to implement a fix?

None

**Comment by azrod** [comment]
Hi @matmb-cld, 

Sorry for the inconvenience and the delay. 
I'm found the origin of the error.
I'm preparing a fix.

Regards
