### ISSUE TITLE
[Bug]: Can't create new ``cloudavenue_vdc`` in existing ``vdc_group``

### ISSUE THREAD

**Issue by Yobar73** [orange-cloudavenue/terraform-provider-cloudavenue#785]
### Terraform Core Version

1.5.5

### Cloud Avenue Provider Version

0.19.0

### Affected Resource(s)

resource "cloudavenue_vdc" "my_vdc" 

### Expected Behavior

When I try to add a new VDC in a existing VDC group, I expect the my_new_vdc resource to be added to my_vdc_group resource.

### Actual Behavior

When I run the previous code, I get an error.

I tried with exporting CLOUDAVENUE_VDC_VALIDATION=false but I have the same result.

### Relevant Error/Panic Output Snippet

```shell
cloudavenue_vdc.my_new_vdc: Creating...
╷
│ Error: Error creating VDC
│ 
│   with cloudavenue_vdc.my_new_vdc,
│   on vdcs.tf line XX, in resource "cloudavenue_vdc" "my_new_vdc":
│   XX: resource "cloudavenue_vdc" "my_new_vdc" {
│ 
│ error on create VDC: ErrorCode:err-0009 - ErrorReason:Application error -
│ ErrorMessage:An unexpected error happened in InfrAPI
```

### Terraform Configuration Files
```hcl
resource "vcd_vdc_group" "my_vdc_group" {
  name                  = "my-vdc-group"
  description           = "my VDC Group"
  starting_vdc_id       = resource.cloudavenue_vdc.my_vdc.id
  participating_vdc_ids = [resource.cloudavenue_vdc.my_vdc.id, resource.cloudavenue_vdc.my_new_vdc.id]
  dfw_enabled           = var.vdc_group_options.dfw_enabled
  default_policy_status = var.vdc_group_options.default_policy_status
}

resource "cloudavenue_vdc" "my_new_vdc" {
  name                  = "my-new-vdc-std"
  description           = "my new VDC Standard"
  cpu_allocated         = 12000
  memory_allocated      = 10
  cpu_speed_in_mhz      = 1200
  billing_model         = "RESERVED"
  disponibility_class   = "ONE-ROOM"
  service_class         = "STD"
  storage_billing_model = "RESERVED"

  storage_profiles =  [
            {
                class   = "silver"
                default = true
                limit   = 100
            },
    ]
}
resource "cloudavenue_vdc" "my_vdc" {
  name                  = "my-vdc"
  description           = "my first VDC Standard"
  cpu_allocated         = 12000
  memory_allocated      = 20
  cpu_speed_in_mhz      = 2200
  billing_model         = "RESERVED"
  disponibility_class   = "ONE-ROOM"
  service_class         = "STD"
  storage_billing_model = "RESERVED"

    storage_profiles =  [
            {
                class   = "silver"
                default = true
                limit   = 100
            },
    ]
}
```

### Steps to Reproduce

1. You have to have an existing vdc_group with one vdc.
2. Add the previous code to add a new vdc
3. Run terraform to create this new vdc

### Would you like to implement a fix?

No

**Comment by azrod** [comment]
Hi @Yobar73 👋, 

Sorry for your problem. 
The error is returned by the CloudAvenue API. 

I'm forwarding your problem  

I will keep you informed

Regards

**Comment by arubert-orange** [comment]
Hello @Yobar73 ,
Curently the minimum value for storage limit is 500. Can you retry updating this value ?
Moreover can you give us the organization id (cav0xxxxxxxxx) on which you are working so that we will be able to debug it easily.
BR

**Comment by azrod** [comment]
> Hello @Yobar73 , Curently the minimum value for storage limit is 500. Can you retry updating this value ? Moreover can you give us the organization id (cav0xxxxxxxxx) on which you are working so that we will be able to debug it easily. BR

Hi @arubert-orange, 
Thank you for considering the problem

Hi @Yobar73 
The allowed values in `cloudavenue_vdc` resource are documented [here](https://registry.terraform.io/providers/orange-cloudavenue/cloudavenue/latest/docs/resources/vdc#serviceclass-std-1)

**Comment by Yobar73** [comment]
In fact, if I set the storage limit to 500. I can create the vdc without problems. 
Sorry for the unnecessary bug. 
I forgot the minimum value for the storage profile.
