### ISSUE TITLE
[Enhancement]: Add "provider_type" argument for "cloudavenue_iam_user"  resource

### ISSUE THREAD

**Issue by jbphilippe-orange** [orange-cloudavenue/terraform-provider-cloudavenue#821]
### Description

When we need to create an IAM user in CloudAvenue, the resource **cloudavenue_iam_user** does not support the **provider_type** argument.  

On VCD provider, we have 3 choices : 
[provider_type](https://registry.terraform.io/providers/vmware/vcd/latest/docs/resources/org_user#provider_type-1)
(Optional) Identity provider type for this user. One of: INTEGRATED, SAML, OAUTH. The default is INTEGRATED.

On CloudAvenue Provider : 

- By default, all users will created as **Local** user. 
- At least on CloudAvenue, we need the option **Local (Integrated)** or **SAML** 

### Affected Resource(s) and/or Data Source(s)

cloudavenue_iam_user

### Potential Terraform Configuration

```terraform
resource "cloudavenue_iam_user" "example" {
  name              = "example"
  role_name         = "Organization Administrator"
  password          = "Password"
  enabled           = true # Default true
  email             = "foo@bar.com"
  telephone         = "1234567890"
  full_name         = "Test User"
  take_ownership    = true # Default true
  deployed_vm_quota = 10   # Default 0
  stored_vm_quota   = 5    # Default 0
  provider_type     = "SAML"
}
```

### Would you like to implement a fix?

None

**Comment by azrod** [comment]
Hi @jbphilippe-orange, 

Thanks for your feature request. 

For the SAML part we are more on the import of an existing user than on the creation of a new user. 
We will think about how to integrate this
