### ISSUE TITLE
[Enhancement]: Add the ability to choose the "app_profile" on cloudavenue_edgegateway_nat_rule

### ISSUE THREAD

**Issue by o-presentini** [orange-cloudavenue/terraform-provider-cloudavenue#822]
### Description

DNAT must be able to route external port to a different local port on VM like vcd provider

### Affected Resource(s) and/or Data Source(s)

cloudavenue_edgegateway_nat_rule

### Would you like to implement a fix?

None

**Comment by azrod** [comment]
Hi @o-presentini,

We have already identified this point and we decided not to implement it for the following reasons:

https://github.com/orange-cloudavenue/terraform-provider-cloudavenue/blob/bc398be4d91cc8bb50bba9e7a9eda71080865156/internal/provider/edgegw/nat_rule_schema.go#L171-L182
