### ISSUE TITLE
[Enhancement]: Export `primary_ip` when using `cloudavenue_edgegateway` Datasource

### ISSUE THREAD

**Issue by jbphilippe-orange** [orange-cloudavenue/terraform-provider-cloudavenue#876]
### Description

With VCD, using **vcd_nsxt_edgegateway** datasource the I can retrieve some attributes like **primary_ip"" which corresponds to the first IP allocated to the EdgeGateway. 

**https://registry.terraform.io/providers/vmware/vcd/latest/docs/data-sources/nsxt_edgegateway**

Today, we don't have this attribute exported in CloudAvenue Provider. 

### Affected Resource(s) and/or Data Source(s)

cloudavenue_edgegateway

### Potential Terraform Configuration

```terraform
data "cloudavenue_edgegateway" "edge_details" {
  name = "tn02i01ocb000XXXXxxxxx"
}

output "edge_details" {
  value = data.cloudavenue_edgegateway.edge_details
}

Changes to Outputs:
  + edge_details = {
      + bandwidth      = 5
      + description    = "Edge Gateway for customer with BSS ID ocb000XXXX"
      + id             = "urn:vcloud:gateway:3e85bddd-7ae0-4ef8-b9a7-f843edb88a27"
      + name           = "tn02i01ocb000XXXXxxxxx"
      + owner_name     = "vdc1"
      + owner_type     = "vdc"
      + tier0_vrf_name = "prvrf02iocb0007231allsp01"

      **+ primary_ip     = "100.73.X.X"**
    }
```

### Would you like to implement a fix?

None

**Comment by azrod** [comment]
Hi @jbphilippe-orange,

What is the use of this primary IP?

Thanks
